function dispparamters(src, eventdata, input)
    disp(input)
%     disp(eventdata)
%     ac=get(gca,'UserData')
%     fc=get(gcf,'UserData')
%     pc=get(gcf,'CurrentPoint')
%     pc=get(gca,'CurrentPoint') 
%   %  lkj=get(gcf,'DisplayName')
%  %   lkj=get(gca,'DisplayName')
end
