function s = VCF_struct
s = struct(...
    'scaf',{}, ...
    'pos',{}, ...
    'id',{}, ...
    'ref',{}, ...
    'alt',{}, ...
    'qual',{}, ...
    'filter',{}, ...
    'info',{}, ...
    'DP',{}, ...
    'AF1',{}, ...
    'AC1',{}, ...
    'DP4',{}, ...
    'MQ',{}, ...
    'FQ',{}, ...
    'PV4',{},...
    'gen1',{}, ...
    'gen2',{}, ...
    'lins',{} ...
    ) ;

return