function s = VCF_struct_dindel
s = struct(...
    'scaf',{}, ...
    'pos',{}, ...
    'ref',{}, ...
    'alt',{}, ...
    'qual',{}, ...
    'af',{}, ...
    'nf',{}, ...
    'nr',{}, ...
    'nfs',{}, ...
    'nrs',{});

return

return

